#http://gmusicproxy.net/#gmusicproxy-google-play-music-proxy-setup-installation

#MPD
'''
You can copy any M3U list generated by the proxy in the playlists registered inside MPD. MPD usually keeps the playlists inside the folder specified by playlist_directory in its configuration file mpd.conf.
curl -s 'http://localhost:9999/get_by_search?type=album&artist=Queen&title=Greatest%20Hits' >
  /var/lib/mpd/playlists/queen.m3u
mpc load queen
mpc play
You can also request a fresh list of songs from a station and add them to the current playlist.
mpc clear
curl -s 'http://localhost:9999/get_new_station_by_search?type=artist&artist=Queen&num_tracks=100' |
  grep -v ^# | while read url; do mpc add "$url"; done
mpc play
'''


